In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("flood.csv")

In [5]:
df.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,3,8,6,6,4,4,6,2,3,2,...,10,7,4,2,3,4,3,2,6,0.450
1,8,4,5,7,7,9,1,5,5,4,...,9,2,6,2,1,1,9,1,3,0.475
2,3,10,4,1,7,5,4,7,4,9,...,7,4,4,8,6,1,8,3,6,0.515
3,4,4,2,7,3,4,1,4,6,4,...,4,2,6,6,8,8,6,6,10,0.520
4,3,7,5,2,5,8,5,2,7,5,...,7,6,5,3,3,4,4,3,4,0.475

In [7]:
df.shape

(50000, 21)

In [9]:
df.isnull().sum()

MonsoonIntensity                   0
TopographyDrainage                 0
RiverManagement                    0
Deforestation                      0
Urbanization                       0
ClimateChange                      0
DamsQuality                        0
Siltation                          0
AgriculturalPractices              0
Encroachments                      0
IneffectiveDisasterPreparedness    0
DrainageSystems                    0
CoastalVulnerability               0
Landslides                         0
Watersheds                         0
DeterioratingInfrastructure        0
PopulationScore                    0
WetlandLoss                        0
InadequatePlanning                 0
PoliticalFactors                   0
FloodProbability                   0
dtype: int64

In [12]:
df.describe()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
count,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000
mean,4.991480,4.984100,5.01594,5.008480,4.989060,4.988340,5.01536,4.988600,5.006120,5.006380,...,5.006060,4.999920,4.984220,4.97982,4.988200,4.984980,5.00512,4.994360,4.990520,0.499660
std,2.236834,2.246488,2.23131,2.222743,2.243159,2.226761,2.24500,2.232642,2.234588,2.241633,...,2.238107,2.247101,2.227741,2.23219,2.231134,2.238279,2.23176,2.230011,2.246075,0.050034
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.285000
25%,3.000000,3.000000,3.00000,3.000000,3.000000,3.000000,3.00000,3.000000,3.000000,3.000000,...,3.000000,3.000000,3.000000,3.00000,3.000000,3.000000,3.00000,3.000000,3.000000,0.465000
50%,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.00000,5.000000,5.000000,0.500000
75%,6.000000,6.000000,6.00000,6.000000,6.000000,6.000000,6.00000,6.000000,6.000000,6.000000,...,6.000000,6.000000,6.000000,6.00000,6.000000,6.000000,6.00000,6.000000,6.000000,0.535000
max,16.000000,18.000000,16.00000,17.000000,17.000000,17.000000,16.00000,16.000000,16.000000,18.000000,...,17.000000,17.000000,16.000000,16.00000,17.000000,19.000000,22.00000,16.000000,16.000000,0.725000

In [18]:
df.duplicated().sum()

0

In [20]:
import sweetviz as sv

In [22]:
EDA_report = sv.analyze(df)
EDA_report.show_html("EDA_Report.html")

                                             |          | [  0%]   00:00 -> (? left)

Report EDA_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [24]:
import webbrowser
webbrowser.open("EDA_Report.html")

True

In [26]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()

In [30]:
X = df.drop("FloodProbability",axis=1)
y = df["FloodProbability"]

In [32]:
X_scaled = scaler.fit_transform(X)

In [36]:
X_scaled

array([[-0.89032073,  1.34250894,  0.44102779, ..., -0.89845678,
        -1.34276933,  0.44944638],
       [ 1.34500358, -0.43806593, -0.00714386, ...,  1.79003104,
        -1.79120216, -0.88623055],
       [-0.89032073,  2.23279638, -0.45531551, ...,  1.34194973,
        -0.8943365 ,  0.44944638],
       ...,
       [-0.44325587, -0.43806593, -0.00714386, ...,  0.44578713,
        -0.44590367, -0.88623055],
       [-0.44325587,  0.00707779, -0.45531551, ..., -0.45037548,
        -2.23963499,  2.6755746 ],
       [-0.44325587,  0.00707779,  0.44102779, ...,  1.34194973,
         2.24469331,  0.89467203]])

In [84]:
X_scaled_df = pd.DataFrame(X_scaled,columns=X.columns)

In [86]:
X_scaled_df

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,IneffectiveDisasterPreparedness,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors
0,-0.890321,1.342509,0.441028,0.446084,-0.440927,-0.443851,0.438597,-1.338607,-0.897767,-1.341169,-0.002255,2.231345,0.890080,-0.441806,-1.334944,-0.891125,-0.440066,-0.898457,-1.342769,0.449446
1,1.345004,-0.438066,-0.007144,0.895983,0.896486,1.801586,-1.788597,0.005106,-0.002739,-0.448954,0.446970,1.784535,-1.335031,0.455973,-1.334944,-1.787539,-1.780394,1.790031,-1.791202,-0.886231
2,-0.890321,2.232796,-0.455316,-1.803411,0.896486,0.005236,-0.452281,0.900915,-0.450253,1.781585,-1.349932,0.890914,-0.444987,-0.441806,1.353026,0.453496,-1.780394,1.341950,-0.894336,0.449446
3,-0.443256,-0.438066,-1.351659,0.895983,-0.886732,-0.443851,-1.788597,-0.442798,0.444776,-0.448954,1.794647,-0.449518,-1.335031,0.455973,0.457036,1.349910,1.347039,0.445787,0.450962,2.230349
4,-0.890321,0.897365,-0.007144,-1.353512,0.004877,1.352498,-0.006842,-1.338607,0.892290,-0.002846,0.896196,0.890914,0.445058,0.007083,-0.886949,-0.891125,-0.440066,-0.450375,-0.894336,-0.441005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-0.890321,0.897365,-0.455316,0.895983,0.004877,1.801586,-0.452281,0.453010,2.234833,-0.448954,-0.451481,0.890914,-0.890009,1.353753,1.353026,0.453496,-1.780394,-0.002294,-0.445904,-1.331456
49996,-0.890321,2.232796,-0.903487,1.345882,-0.886732,-0.892938,-0.452281,-0.442798,-0.897767,2.673800,1.345421,1.337724,0.445058,-0.890696,0.457036,-0.442918,-0.440066,-1.346538,-0.445904,0.004221
49997,-0.443256,-0.438066,-0.007144,0.895983,-1.332536,-1.791113,-0.452281,0.005106,0.444776,0.889369,0.896196,-0.449518,0.445058,-0.441806,-1.782939,0.005289,-1.780394,0.445787,-0.445904,-0.886231
49998,-0.443256,0.007078,-0.455316,-0.453714,0.450681,-0.892938,2.220352,-1.338607,0.444776,2.673800,-0.002255,0.444103,-0.890009,-0.441806,0.905031,0.453496,-1.333618,-0.450375,-2.239635,2.675575
49999,-0.443256,0.007078,0.441028,-0.903613,0.004877,0.454324,-0.006842,-0.442798,1.787318,2.227693,0.446970,-1.343139,-0.444987,-0.441806,0.009041,0.453496,0.900263,1.341950,2.244693,0.894672

In [42]:
from sklearn.decomposition import PCA

In [44]:
pca = PCA(n_components=0.90)

In [46]:
X_pca = pca.fit_transform(X_scaled)

In [51]:
correlation_matrix = df.corr()

In [70]:
correlation_matrix

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
MonsoonIntensity,1.000000,-0.003470,0.002247,-0.005384,0.005092,0.005959,0.002790,-0.003191,0.002723,-0.003723,...,-0.000118,-0.004600,-0.002315,-0.008859,0.001763,-0.003597,0.005938,0.003455,0.005402,0.224081
TopographyDrainage,-0.003470,1.000000,0.002492,0.002046,0.000116,-0.002288,-0.004472,0.010675,-0.004550,-0.007272,...,-0.001608,-0.000717,-0.002040,0.005312,0.003654,0.005887,0.003515,0.005276,0.008191,0.229414
RiverManagement,0.002247,0.002492,1.000000,0.004808,-0.009651,0.007199,0.007697,-0.000389,0.003635,0.009253,...,0.002171,-0.000111,-0.004339,0.000097,0.000604,-0.001382,0.002012,0.000364,-0.006323,0.228917
Deforestation,-0.005384,0.002046,0.004808,1.000000,-0.011325,0.000517,-0.000728,-0.000823,0.002929,-0.003507,...,-0.001060,-0.003019,0.005258,0.002171,-0.002093,0.000138,-0.000718,-0.001108,0.001242,0.220237
Urbanization,0.005092,0.000116,-0.009651,-0.011325,1.000000,0.007478,0.000268,-0.001287,-0.001391,-0.011386,...,-0.005281,-0.000881,-0.000651,-0.003479,0.004222,0.002154,0.013263,-0.000864,-0.002418,0.220867
ClimateChange,0.005959,-0.002288,0.007199,0.000517,0.007478,1.000000,-0.002889,0.001514,-0.003362,0.000075,...,-0.007587,-0.001467,0.000689,0.003023,0.003281,-0.008334,-0.000547,-0.000186,-0.004453,0.220986
DamsQuality,0.002790,-0.004472,0.007697,-0.000728,0.000268,-0.002889,1.000000,0.003239,0.001743,0.001638,...,0.004165,-0.009503,0.000436,0.005322,-0.004001,0.006856,-0.000662,0.001535,0.001699,0.227467
Siltation,-0.003191,0.010675,-0.000389,-0.000823,-0.001287,0.001514,0.003239,1.000000,-0.003911,0.000158,...,-0.008296,-0.003564,-0.001866,0.003682,0.003045,-0.002484,0.007903,0.011918,-0.001597,0.226544
AgriculturalPractices,0.002723,-0.004550,0.003635,0.002929,-0.001391,-0.003362,0.001743,-0.003911,1.000000,-0.006564,...,0.000648,-0.003708,0.004142,0.004371,0.003248,0.001678,-0.007963,-0.002221,-0.001280,0.221846
Encroachments,-0.003723,-0.007272,0.009253,-0.003507,-0.011386,0.000075,0.001638,0.000158,-0.006564,1.000000,...,-0.005960,-0.006591,-0.003032,0.003679,0.002774,0.003874,0.005706,0.001380,-0.007547,0.218259
IneffectiveDisasterPreparedness,0.002358,0.001328,0.006269,0.002312,0.001289,-0.005455,-0.001116,0.000667,0.003387,0.001461,...,0.003551,0.001399,-0.001763,-0.000245,0.000149,-0.004047,-0.004337,0.003628,0.001102,0.225126
DrainageSystems,-0.000118,-0.001608,0.002171,-0.001060,-0.005281,-0.007587,0.004165,-0.008296,0.000648,-0.005960,...,1.000000,0.008439,0.003746,-0.002762,-0.002501,-0.000285,-0.006217,-0.008116,0.001197,0.217895
CoastalVulnerability,-0.004600,-0.000717,-0.000111,-0.003019,-0.000881,-0.001467,-0.009503,-0.003564,-0.003708,-0.006591,...,0.008439,1.000000,0.003260,0.002213,-0.004779,0.001622,-0.007103,-0.009539,-0.003269,0.215187
Landslides,-0.002315,-0.002040,-0.004339,0.005258,-0.000651,0.000689,0.000436,-0.001866,0.004142,-0.003032,...,0.003746,0.003260,1.000000,0.003552,0.002840,0.001621,-0.002325,-0.009414,0.003839,0.222991
Watersheds,-0.008859,0.005312,0.000097,0.002171,-0.003479,0.003023,0.005322,0.003682,0.004371,0.003679,...,-0.002762,0.002213,0.003552,1.000000,0.004844,0.001352,-0.007696,0.009347,-0.003130,0.228152
DeterioratingInfrastructure,0.001763,0.003654,0.000604,-0.002093,0.004222,0.003281,-0.004001,0.003045,0.003248,0.002774,...,-0.002501,-0.004779,0.002840,0.004844,1.000000,0.000541,-0.000104,0.007258,0.004304,0.229444
PopulationScore,-0.003597,0.005887,-0.001382,0.000138,0.002154,-0.008334,0.006856,-0.002484,0.001678,0.003874,...,-0.000285,0.001622,0.001621,0.001352,0.000541,1.000000,0.003615,-0.002177,0.007371,0.226928
WetlandLoss,0.005938,0.003515,0.002012,-0.000718,0.013263,-0.000547,-0.000662,0.007903,-0.007963,0.005706,...,-0.006217,-0.007103,-0.002325,-0.007696,-0.000104,0.003615,1.000000,-0.003828,0.002627,0.223732
InadequatePlanning,0.003455,0.005276,0.000364,-0.001108,-0.000864,-0.000186,0.001535,0.011918,-0.002221,0.001380,...,-0.008116,-0.009539,-0.009414,0.009347,0.007258,-0.002177,-0.003828,1.000000,-0.004491,0.223329
PoliticalFactors,0.005402,0.008191,-0.006323,0.001242,-0.002418,-0.004453,0.001699,-0.001597,-0.001280,-0.007547,...,0.001197,-0.003269,0.003839,-0.003130,0.004304,0.007371,0.002627,-0.004491,1.000000,0.225009
FloodProbability,0.224081,0.229414,0.228917,0.220237,0.220867,0.220986,0.227467,0.226544,0.221846,0.218259,...,0.217895,0.215187,0.222991,0.228152,0.229444,0.226928,0.223732,0.223329,0.225009,1.000000

In [89]:
from sklearn.model_selection import train_test_split

In [95]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [97]:
from sklearn.linear_model import LinearRegression

In [99]:
model = LinearRegression()

In [178]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)
X_train_scaled = pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled,columns=X_test.columns)

In [190]:
y_pred = model.predict(X_test_scaled)

In [192]:
from sklearn.metrics import r2_score

In [194]:
r2_score(y_test,y_pred)

-98.52682506808422

In [196]:
y_pred_train = model.predict(X_train_scaled)

In [198]:
r2_score(y_train,y_pred_train)

-99.25444967740972

In [200]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [202]:
mean_absolute_error(y_test,y_pred)

0.4994360000000002

In [204]:
mean_squared_error(y_test,y_pred)

0.2502036608424839

In [146]:
from sklearn.ensemble import RandomForestRegressor

In [160]:
model1 = RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42)

In [206]:
model1.fit(X_train_scaled,y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=42)

In [207]:
y_pred1 = model1.predict(X_test_scaled)

In [171]:
r2_score(y_test,y_pred1)

0.5756296922286843

In [210]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Ridge, Lasso

models = {
    "DecisionTree": DecisionTreeRegressor(),
    "GradientBoosting": GradientBoostingRegressor(),
    "SVR": SVR(),
    "Ridge": Ridge(),
    "Lasso": Lasso()
}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    r2 = r2_score(y_test, y_pred)
    print(f"{name} R2 Score: {r2:.4f}")

DecisionTree R2 Score: 0.1376
GradientBoosting R2 Score: 0.7838
SVR R2 Score: 0.6977
Ridge R2 Score: 0.9999
Lasso R2 Score: -0.0000

In [213]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import GradientBoostingRegressor
from scipy.stats import randint as sp_randint
from scipy.stats import uniform

param_dist = {
    'n_estimators': sp_randint(50, 200),
    'max_depth': sp_randint(2, 7),
    'learning_rate': uniform(0.01, 0.2)
}

random_search = RandomizedSearchCV(
    GradientBoostingRegressor(random_state=42),
    param_distributions=param_dist,
    n_iter=20,       
    cv=5,
    scoring='r2',
    random_state=42,
    n_jobs=-1         
)

random_search.fit(X_train_scaled, y_train)
print("Best Params:", random_search.best_params_)
print("Best R2 Score:", random_search.best_score_)

Best Params: {'learning_rate': 0.1425044568707964, 'max_depth': 3, 'n_estimators': 183}
Best R2 Score: 0.9526054592144284

In [215]:
import joblib as jb

In [221]:
jb.dump(random_search.best_estimator_,"Flood_prediction_model.pkl")

['Flood_prediction_model.pkl']

In [223]:
my_model = jb.load("Flood_prediction_model.pkl")